#This travis.yml deploys the deploy/heroku outcome of the "grunt buildHeroku" task
language: java
jdk: oraclejdk8
install:
  - npm install
  - gem install compass

before_deploy:
  - "grunt buildHeroku"
  - "shopt -s extglob dotglob"
  - "mv deploycfg/* deploy/heroku"
  - "ls deploy/heroku -a"
  - "rm -rf !(deploy)"
  - "ls -a"
  - "mv deploy/heroku/* ."
  - "ls -a"
  - "mv HerokuDatabaseConfiguration.java src/main/java/de/senlima/senlima/config/"
  - "ls src/main/java/de/senlima/senlima/config/ -a"
  - "rm -rf deploy"
  - "ls -a"


deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: nOHe20M3suthiT7QYK1KEtRsNcJYiZS9BTK2gH0QzwD3K9qsY07fl+h+oX6DNhgNxSpqK5IgNmzjEh/Adh1ZqK+xx7u9AOeAzljTqVNuxZM4YEl2Wa2lqdxLVQTgnXJWZ+paX9kGuPI4oKU3navs7aOLcIlXsCJkys9qJRfG0RU=
  app:
    development: senlima-dev
    master: senlima
